name: Deploy to GitHub Pages

# 触发条件: 当 docs 分支有推送时运行
on:
  push:
    branches:
      - docs  # 监听 docs 分支的推送

# 权限配置
permissions:
  contents: write  # 允许写入 main 分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'  # 使用 npm 缓存

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install --legacy-peer-deps    

      # Step 4: 清除旧的 actions 缓存
      - name: Clear old actions cache
        run: sudo rm -rf ${{ github.workspace }}/_actions/JamesIves/github-pages-deploy-action

      - name: Grant execute permission for vuepress
        run: chmod +x node_modules/.bin/vuepress
      
      - name: Build VuePress
        run: npm run docs:build
      

      # Step 5.5: 添加 .nojekyll 文件，确保 GitHub Pages 正确渲染
      - name: Create .nojekyll file
        run: echo '' > docs/.vuepress/dist/.nojekyll

      # Step 6: 部署到 main 分支的根目录
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3  # 确保使用特定版本
        with:
          branch: main  # 将文件部署到 main 分支
          folder: docs/.vuepress/dist  # 使用 dist 目录作为静态文件源

